"""
Deterministic mock restaurant data for TripResQ demo scenario.
Near the Goa destination to match the demo trip.
"""

RESTAURANTS = [
    {
        "id": "r-goa-1",
        "city": "Goa",
        "name": "Fisherman's Wharf",
        "cuisine": "Goan Seafood, Prawn Curry, Xacuti",
        "distance": 0.6,
        "cost": 1200,
        "rating": 4.7,
        "tags": ["Local Specialties"],
        "open247": False,
        "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60",
    },
    {
        "id": "r-goa-2",
        "city": "Goa",
        "name": "Gunpowder",
        "cuisine": "South Indian & Kerala Cuisine, Dosa, Appam",
        "distance": 1.3,
        "cost": 900,
        "rating": 4.5,
        "tags": ["Pure Veg", "Local Specialties"],
        "open247": False,
        "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=500&auto=format&fit=crop&q=60",
    },
    {
        "id": "r-goa-3",
        "city": "Goa",
        "name": "Baba Au Rhum",
        "cuisine": "French Bakery, Croissants, Artisan Coffee",
        "distance": 0.8,
        "cost": 700,
        "rating": 4.4,
        "tags": ["Fast Delivery"],
        "open247": True,
        "image": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60",
    },
    {
        "id": "r-goa-4",
        "city": "Goa",
        "name": "Vinayak Family Restaurant",
        "cuisine": "Pure Veg Thali, North Indian, Gujarati",
        "distance": 2.0,
        "cost": 500,
        "rating": 4.3,
        "tags": ["Pure Veg", "Fast Delivery"],
        "open247": False,
        "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=60",
    },
    {
        "id": "r-goa-5",
        "city": "Goa",
        "name": "Thalassa Greek Taverna",
        "cuisine": "Greek Mediterranean, Seafood, Sunset Dining",
        "distance": 3.5,
        "cost": 2200,
        "rating": 4.8,
        "tags": ["Local Specialties"],
        "open247": False,
        "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&auto=format&fit=crop&q=60",
    },
    {
        "id": "r-goa-6",
        "city": "Goa",
        "name": "24x7 Beach Shack Express",
        "cuisine": "Quick Bites, Fish Fry, Cold Drinks",
        "distance": 0.3,
        "cost": 350,
        "rating": 4.0,
        "tags": ["Fast Delivery", "Open 24/7"],
        "open247": True,
        "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&auto=format&fit=crop&q=60",
    },
]
